name: Run screenshot tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #Setup Node
      with:
        node-version: '16.15.0'
    - name: Run screenshot Tests
      run: |
        npm ci
        npm run test:screenshots -- --build=es2018.en
        npm run test:screenshots -- --build=es2018

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: screenshots
          path: |
            src/**/__image_snapshots__/**/*.png
